### ISSUE TITLE
Statuscolors: Some fonts cause text truncation

### ISSUE THREAD

**Issue by jgrar** [jgrar/dwm-patches#4]
First raised: https://bbs.archlinux.org/viewtopic.php?pid=1597306#p1597306

Fonts affected (of the fonts I have on my system): 
- Andale
- Arial
- Bookman
- Cantarell
- Century
- Chancery
- ClearlyU
- Comic
- DejaVu
- DejaVu Sans
- East
- Estrangelo
- Georgia
- Goha-Tibeb
- Impact
- Material
- Newspaper
- Nimbus
- Palladio
- Serto
- Standard
- Times
- Trebuchet
- URW
- Verdana

Notes:
It seems monospaced fonts are not affected.

**Comment by LemonBoy** [comment]
It's quite simple, while `curfont->xfont->max_advance_width` is often the right cell size for monospaced fonts that's not quite true for proportional ones which have variable cell sizes.
So it all boils down to replacing that with `drw_font_getexts_width(curfont, "\x01", 1)`, at least that's enough to make the original patch work just fine with Liberation Sans which exposed this problem before.

**Comment by jgrar** [comment]
Thanks @LemonBoy, that helps a lot. I had to put this on hold due to assignments. I should have a break soon to get a fix sorted out.

**Comment by jgrar** [comment]
@LemonBoy Tested your fix with all fonts (installed on my system) and see no truncation issues, thanks again for your help, much appreciated!

**Comment by ghost** [comment]
Does you commit fix problem with DajVu Sans font?

**Comment by jgrar** [comment]
@thedieselspaceship yes ( :
