### ISSUE TITLE
Statuscolors: bg color doesn't fill from initial padding area

### ISSUE THREAD

**Issue by jgrar** [jgrar/dwm-patches#6]
From #5 

> ... doesn't draw the specified bg color from the beginning of the status box area. This is due to the text being padded on the boundary and the initial fill color set to normal. So if you specify something else at the beginning of the status text the padding area will fill with the normal bg color, not the user's.

**Comment by Vusluk** [comment]
Thanks for the patch. I'm trying to make handsome statusbar without conky and dzen2. If you fix this issue, it will be very useful.
